language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t darkidas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true darkidas/docker-react npm run test